### ISSUE TITLE
Batch Processing for Embedding Generation

### ISSUE THREAD

**Issue by adityaghai07** [adityaghai07/GenRAG#11]
## Description
Implement batch processing for embedding generation to improve performance.
Current implementation iterates through chunks individually, which is computationally inefficient. By using batch processing, we can achieve approximately 4x speed improvement.

## Objectives
- Improve embedding generation performance
- Reduce computational overhead

## # Current inefficient approach in `embed_model.py`
```python

for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])
```

## Technical Approach
- Transition from sequential processing to batch encoding
- Leverage `batch_size` parameter for optimized processing

## Proposed Solution
```python
# Batch processing implementation
text_chunk_embeddings = embedding_model.encode(
    text_chunks,
    batch_size=32,  # Configurable batch size
    convert_to_tensor=True  # Optional tensor conversion
)
```

## Expected Outcomes
- Approximately 4x speed improvement
- Reduced processing time for large document collections

## Performance Considerations
- Experiment with different batch sizes (16, 32, 64)
- Benchmark processing times for various document sizes

**Comment by VishalPainjane** [comment]
I would like to work on this issue...!

**Comment by adityaghai07** [comment]
@VishalPainjane  I have assigned you this issue.
